---
title: "notes"
editor: visual
---

```{r setup}
library(tidyverse)
library(ggthemes)
library(socviz)


# Setting a default ggplot theme 
theme_set(theme_fivethirtyeight() +
          theme(strip.background = element_rect(fill="lightgray"),
                axis.title.x = 
                  element_text(angle = 0,
                               size = rel(1.33),
                               margin = margin(10,0,0,0)),
                axis.title.y = 
                  element_text(angle = 90,
                               size = rel(1.33),
                               margin = margin(0,10,0,0))
                )
          )
```

```{r}
organdata <- socviz::organdata

DT::datatable(organdata)
```
## Classwork 5 q2d
```{r}
ggplot(organdata, aes(x = roads, y = donors, color = world)) +
  geom_point(alpha = 1) +
  labs(x = "roads", y = "donors") +
  scale_color_manual(values = c("Corporatist" = "blue", "Liberal" = "orange", "SocDem" = "red")) +
  scale_y_continuous(breaks = seq(5,25, 10)) +
  theme_minimal() +
  theme(legend.position = "bottom") 
```

## Classwork 5 q2g
```{r}
organdata %>% 
  ggplot(aes(x = roads,
         y = donors, color = consent_law)) +
  geom_point(show.legend = F) +
  labs(title = "By Consent Law", 
        x = "Road Deaths",
        y = "Donor Procurment",
        color = "Legal Regime:") +
  scale_color_manual = c("steelblue", "darkorange") +
  theme(plot.title = element_text(color = "brown", size = rel(2)))
```


## Add labels and make notes
```{r}
p <- ggplot(data = by_country,
            mapping = 
              aes(x = roads_mean, 
                  y = donors_mean))
p + geom_point() + 
  geom_text(mapping = 
              aes(label = country))
```

```{r}
p + geom_point() + 
  geom_text(mapping = 
              aes(label = country), 
            hjust = 0)
```

```{r}
install.packages("ggrepel")
library(ggrepel)
```

```{r}
socviz::elections_historic |> select(2:7) 
```

```{r}
p <- ggplot(elections_historic, aes(x = popular_pct, y = ec_pct,
                                    label = winner_label))
```

```{r}
p <- p + 
    geom_hline(yintercept = 0.5, 
               linewidth = 1.4, 
               color = "gray80") +
    geom_vline(xintercept = 0.5, 
               linewidth = 1.4, 
               color = "gray80") +
    geom_point() +
    geom_text_repel()
p
```

```{r}
p <- p + 
     scale_x_continuous(
       labels = scales::percent) +
     scale_y_continuous(
       labels = scales::percent) 
p
```

```{r}
p_title <- "Presidential Elections: Popular & Electoral College Margins"
p_subtitle <- "1824-2016"
p_caption <- "Data for 2016 are provisional."
x_label <- "Winner's share of Popular Vote"
y_label <- "Winner's share of Electoral College Votes"

p + labs(x = x_label, 
         y = y_label, 
         title = p_title, 
         subtitle = p_subtitle,
         caption = p_caption)
```

```{r}
# creating a dummy variable for labels
organdata <- organdata |> 
  mutate(ind = ccode %in% 
                  c("Ita", "Spa") & 
               year > 1998)  

p <- ggplot(data = organdata,
            mapping = 
              aes(x = roads, 
                  y = donors, 
                  color = ind))
p + 
  geom_point() +
  geom_text_repel(
    data = filter(organdata, ind),
    mapping = aes(label = ccode)) +
  guides(label = "none", 
         color = "none")
```

```{r}
p <- ggplot(data = organdata, 
            mapping = 
              aes(x = roads, 
                  y = donors))
p + geom_point() + 
  annotate(geom = "text", 
           x = 91, y = 33,
           label = "A surprisingly high \n recovery rate.",
           hjust = 0)
```

```{r}
p <- ggplot(data = organdata,
            mapping = aes(x = roads, y = donors))
p + geom_point() +
    annotate(geom = "rect", 
             xmin = 125, xmax = 155,
             ymin = 30, ymax = 35, 
             fill = "red", 
             alpha = 0.2) + 
    annotate(geom = "text", 
             x = 157, y = 33,
             label = "A surprisingly high \n recovery rate.", 
             hjust = 0)
```

```{r}
p <- ggplot(mpg, aes(displ, hwy)) +
  geom_point(
    data = 
      filter(mpg, 
             manufacturer == "subaru"), 
    color = "orange", 
    size = 3) +
  geom_point() 
p + 
  annotate(geom = "point", 
           x = 5.5, y = 40, 
           colour = "orange", 
           size = 3) + 
  annotate(geom = "point", 
           x = 5.5, y = 40) + 
  annotate(geom = "text", 
           x = 5.6, y = 40, 
           label = "subaru", 
           hjust = "left")
```
```{r}
p + 
  annotate(
    geom = "curve", 
    x = 4, y = 35, 
    xend = 2.65, yend = 27, 
    curvature = .3, 
    arrow = 
      arrow(length = unit(2, "mm"))
  ) +
  annotate(geom = "text", 
           x = 4.1, y = 35, 
           label = "subaru", 
           hjust = "left")
```

#Classwork 6

```{r}
#data
gapminder <- gapminder::gapminder
```



```{r}
electricity <- read_csv(
  'https://bcdanl.github.io/data/electricity-usa-chn.csv')
```
# Classwork 6 Question 2a
```{r}
electricity %>% 
  ggplot(aes(x = year,
             y = value,
             color = energy)) +
  geom_line() +
  facet_wrap( ~ iso3c) +
  labs( x = "year",
        y = "Electricity Generation (TWh)",
        color = "Energy") +
  theme(strip.background = element_rect(fill = "lightgray"),
         axis.title.y = element_text(angle = 0), 
        legend.position = "top")
        
```
#Question 2b
```{r}
electricity_new <- electricity %>% 
  arrange(iso3c, energy) %>% 
  group_by(iso3c, year) %>% 
  mutate(tot = sum(value)) %>% 
  mutate(pct = value/tot)


```
```{r}
electricity_new %>% 
  ggplot(aes(x = year,
             y = value,
             color = energy)) +
  geom_line() +
  facet_wrap( ~ iso3c) +
  labs( x = "year",
        y = "Electricity Generation (TWh)",
        color = "Energy") +
  theme(strip.background = element_rect(fill = "lightgray"),
         axis.title.y = element_text(angle = 0), 
        legend.position = "top")
        
```
# Notes
```{r}
# install.pacakges("RColorBrewer")
library(RColorBrewer)
```

##Scale_color_brewer with palette
```{r}
p <- ggplot(data = organdata,
            mapping = 
              aes(x = roads, 
                  y = donors, 
                  color = world))

p + geom_point(size = 2,
               alpha = .5) + 
  scale_color_brewer(
    palette = "Set2") +
  theme(legend.position = "top")
```

```{r}
hdi_corruption <- read_csv(
  'https://bcdanl.github.io/data/hdi_corruption.csv')
```

```{r}
library(ggplot2)
library(ggrepel)


x_label <- "Corruption Perceptions Index, 2014 (100 = least corrupt)"
y_label <- "Human Development Index, 2014 (1.0 = most developed)"


ggplot(data = hdi_corruption,
            mapping = 
              aes(x = cpi, 
                  y = hdi, 
                  color = region)) +
  labs(x = x_label,
       y = y_label) +
 

geom_point(size = .5,
               alpha = .5) +
  geom_smooth(color = "blue", method = "loess", se = FALSE) +
  geom_text(data = hdi_corruption[hdi_corruption$country %>% c("Argentina", "China", "Egypt", "South Africa", "Senegal", "Greece", "United States", "Germany", "Norway", "Singapore"),], aes(label = country), color = "black") +
  theme(legend.position = "top")
```

